<a href="https://colab.research.google.com/github/Shivang-Quantum/QuantaPytha/blob/main/Deep%20Learning/Pytorch_Basics_Binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

In [6]:
# Generate some data
np.random.seed(911)
X_data=np.random.uniform(low=1,high=10,size=100)
X_data

noise=np.random.normal(loc=0,scale=0.5,size=100)
noise


Y_data= ((X_data + noise)>5).astype(int)

In [9]:
X_data

array([1.80580824, 1.70786706, 8.36514055, 4.46301493, 3.23087817,
       2.31301871, 5.73626086, 6.70993569, 5.2064843 , 4.82905271,
       7.96982143, 8.0841686 , 6.3128683 , 7.2232709 , 7.90902243,
       4.51526287, 4.97545521, 5.70404285, 8.77204851, 3.63577717,
       5.27416207, 9.7298942 , 2.60612457, 6.12682674, 3.38692288,
       6.26551007, 3.36377314, 8.07116936, 1.93228211, 6.87665851,
       2.62961139, 2.2079983 , 3.57527495, 9.39473986, 9.5018369 ,
       8.15084609, 8.42229076, 9.10005463, 4.06142701, 3.45028682,
       5.63350694, 7.90679057, 8.98607938, 2.35945665, 9.71638311,
       6.79291426, 1.46786212, 9.78847144, 9.91079893, 9.50400404,
       7.22208091, 1.40205957, 4.0597982 , 7.92446408, 4.07163266,
       2.31018938, 5.58185962, 9.87307562, 2.11004803, 4.38528251,
       9.02411417, 7.27901673, 2.73386723, 3.58070689, 5.35996125,
       1.31423973, 8.13563537, 3.75487808, 6.25071029, 8.04274882,
       3.3621992 , 6.73081966, 7.36508348, 6.78952528, 4.96819

In [10]:
noise

array([ 0.6446309 , -0.44022584,  0.63701666, -0.05518925, -0.26200466,
        0.49734892,  0.26453406, -0.42122153,  0.28841215, -0.20098418,
       -0.04544686, -0.95119508, -0.90230471,  0.54039583,  0.48261249,
       -0.76809556, -0.27264849,  0.40774833,  0.42413242,  0.11497342,
       -0.27343174, -0.09640996,  0.1527389 , -0.1767682 ,  0.32755571,
        0.20398987,  0.26001359,  0.9738931 , -0.81303844, -0.59849589,
        0.02294968,  0.19065872,  0.31257969, -0.87312427,  0.68414431,
       -0.37371207,  0.39655861, -0.41310319,  0.47082358,  0.33288437,
        0.14204541, -0.07715436, -0.12588315, -0.19790631, -0.66628537,
       -0.24697106,  0.09755209,  0.02682145,  0.92861146,  0.11354205,
       -0.96947423, -0.34928798, -0.16635877, -0.31960176,  0.16499934,
       -0.39186487, -0.18555575, -0.36895558, -0.09820627,  0.06545091,
       -0.44126033,  0.41471172,  0.48774081, -0.2300652 ,  0.91678643,
       -0.05915641, -0.29105732, -0.14230953,  0.58230411, -0.79

In [11]:
Y_data

array([0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1])

In [12]:
# Crete a DF
data={"feature":X_data,"target":Y_data}
df=pd.DataFrame(data)
df

feature  target
0   1.805808       0
1   1.707867       0
2   8.365141       1
3   4.463015       0
4   3.230878       0
..       ...     ...
95  4.025322       0
96  4.948794       0
97  8.751693       1
98  8.882798       1
99  9.978164       1

[100 rows x 2 columns]

In [15]:
X=torch.tensor(df['feature'].values,dtype=torch.float32).view(-1,1)
Y=torch.tensor(df['target'].values,dtype=torch.float32).view(-1,1)

X

tensor([[1.8058],
        [1.7079],
        [8.3651],
        [4.4630],
        [3.2309],
        [2.3130],
        [5.7363],
        [6.7099],
        [5.2065],
        [4.8291],
        [7.9698],
        [8.0842],
        [6.3129],
        [7.2233],
        [7.9090],
        [4.5153],
        [4.9755],
        [5.7040],
        [8.7720],
        [3.6358],
        [5.2742],
        [9.7299],
        [2.6061],
        [6.1268],
        [3.3869],
        [6.2655],
        [3.3638],
        [8.0712],
        [1.9323],
        [6.8767],
        [2.6296],
        [2.2080],
        [3.5753],
        [9.3947],
        [9.5018],
        [8.1508],
        [8.4223],
        [9.1001],
        [4.0614],
        [3.4503],
        [5.6335],
        [7.9068],
        [8.9861],
        [2.3595],
        [9.7164],
        [6.7929],
        [1.4679],
        [9.7885],
        [9.9108],
        [9.5040],
        [7.2221],
        [1.4021],
        [4.0598],
        [7.9245],
        [4.0716],
        [2

In [16]:
Y

tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
      

In [20]:
class my_LinearRegression(nn.Module):
  def __init__(self,input_size,hidden_size1,hidden_size2,output_size):
    super().__init__()

    self.layer1=nn.Linear(input_size,hidden_size1)
    self.relu1=nn.ReLU()

    self.layer2=nn.Linear(hidden_size1,hidden_size2)
    self.sigmoid2=nn.Sigmoid()

    self.output=nn.Linear(hidden_size2,output_size)

  def forward(self,x):
    x=self.layer1(x)
    x=self.relu1(x)
    x=self.layer2(x)
    x=self.sigmoid2(x)
    x=self.output(x)
    return x

In [19]:
input_size=1
hidden_size1=3
hidden_size2=7
output_size=1 # Bnary

model=my_LinearRegression(input_size,hidden_size1,hidden_size2,output_size)


In [21]:
criterion=nn.BCEWithLogitsLoss()
optimizer=optim.SGD(model.parameters(),lr=0.01)

In [22]:
num_epochs=100
for epochs in range(num_epochs):

  #forward pass
  output=model(X)
  loss = criterion(output,Y)

  #backward pass
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  # print loss
  if (epochs + 1)%10==0:
    print(f"EPOCH {epochs+1}/{num_epochs},LOSS {loss.item():.4f}")



EPOCH 10/100,LOSS 0.6634
EPOCH 20/100,LOSS 0.6608
EPOCH 30/100,LOSS 0.6584
EPOCH 40/100,LOSS 0.6562
EPOCH 50/100,LOSS 0.6542
EPOCH 60/100,LOSS 0.6524
EPOCH 70/100,LOSS 0.6507
EPOCH 80/100,LOSS 0.6491
EPOCH 90/100,LOSS 0.6477
EPOCH 100/100,LOSS 0.6463


In [23]:
with torch.no_grad():
  print(f'Trained Param: Layer 1 weight {model.layer1.weight.data}, Layer 1 Bias {model.layer1.bias.data}')
  print(f'Trained Param: Layer 1 weight {model.layer2.weight.data}, Layer 1 Bias {model.layer2.bias.data}')

Trained Param: Layer 1 weight tensor([[-0.1474],
        [ 0.0082],
        [ 0.6464]]), Layer 1 Bias tensor([0.2973, 0.3350, 0.2955])
Trained Param: Layer 1 weight tensor([[ 0.0061, -0.5156, -0.1653],
        [-0.4183,  0.1590, -0.1408],
        [-0.4946, -0.2302,  0.4380],
        [-0.3028, -0.3653,  0.0575],
        [ 0.3370,  0.4298, -0.4973],
        [-0.2380, -0.1898,  0.1199],
        [-0.1453, -0.0642,  0.0565]]), Layer 1 Bias tensor([ 0.1053,  0.4903,  0.2320, -0.0600, -0.3337,  0.4653,  0.3072])


In [29]:
with torch.no_grad():
  prediction=torch.sigmoid(model(X)).numpy()


In [31]:
df['prob']=prediction
df['pred']=(prediction>0.5).astype(int)
acc=np.mean(df['pred']==df['target'])

In [34]:
df
acc

0.59